[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-aarch64"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"aur:timeshift",
 	"pkg:ame",
	"pkg:grub",
	"pkg:jade",
	"pkg:jade-gui",
	"pkg:malachite",
	"pkg:pkg-warner",
	"pkg:zramd",
]

[repositories.urls]
aur = "https://aur.archlinux.org/{}"
pkg = "https://github.com/crystal-linux-packages/{}"
