[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-any"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"pkg:crystal-keyring",
	"pkg:onyx",
	"pkg:wallpapers",
	"pkg:grub-theme",
	"pkg:base",
	"pkg:crystal-dev",
	"pkg:filesystem",
	"pkg:lsb-release",
	"pkg:neofetch",
	"pkg:pfetch",
	"pkg:pkg-warner",
	"pkg:onyx",
	"pkg:gnome-shell-extension-desktop-icons-neo",
	"pkg:gnome-shell-extension-caffeine",
	"aur:timeshift",
	"aur:timeshift-autosnap",
	"aur:gnome-shell-extension-dash-to-panel",
	"aur:gnome-shell-extension-arch-update",
	"aur:gnome-shell-extension-gsconnect",
]

[repositories.urls]
pkg = "https://github.com/crystal-linux/pkgbuild.{}"
aur = "https://aur.archlinux.org/{}"
