[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-any"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"age:arch-update",
	"age:dash-to-panel",
	"age:gsconnect",
	"aur:timeshift-autosnap",
	"gse:caffeine",
	"gse:desktop-icons-neo",
	"pkg:base",
	"pkg:crystal-dev",
	"pkg:crystal-keyring",
	"pkg:filesystem",
	"pkg:grub-theme",
	"pkg:lsb-release",
	"pkg:neofetch",
	"pkg:onyx",
	"pkg:onyx",
	"pkg:pfetch",
	"pkg:wallpapers",
]

[repositories.urls]
age = "https://aur.archlinux.org/gnome-shell-extension-{}"
aur = "https://aur.archlinux.org/{}"
gse = "https://github.com/crystal-linux/pkgbuild.gnome-shell-extension-{}"
pkg = "https://github.com/crystal-linux/pkgbuild.{}"
