[base]
mode = "repository"
smart_pull = true

[mode.repository]
name = "crystal-any"
build_on_update = true

[mode.repository.signing]
enabled = true
on_gen = true

[repositories]
repos = [
	"age:arch-update",
	"age:dash-to-panel",
	"age:gsconnect",
	"aur:timeshift-autosnap",
	"age:caffeine",
	"age:desktop-icons-neo",
	"pkg:crystal-dev",
	"pkg:crystal-keyring",
	"pkg:crystal-mirrorlist",
	"pkg:grub-theme",
	"pkg:neofetch",
	"pkg:onyx",
	"pkg:wallpapers",
	"pkg:jade-tui",
	"pkg:crystal-core",
	"pkg:crystal-branding",
]

[repositories.urls]
age = "https://aur.archlinux.org/gnome-shell-extension-{}"
aur = "https://aur.archlinux.org/{}"
gse = "https://github.com/crystal-linux-packages/gnome-shell-extension-{}"
pkg = "https://github.com/crystal-linux-packages/{}"
